apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas:
  selector:
    matchLabels:
      app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
          - name: web
            image: jonasRibeiro/conversao-temperatura
            ports:
              - containerPort: 80